site_name: ERC Handbook
site_url: https://erc-bpgc.github.io/handbook/

site_description: A beginners guide to all things robotics
site_author: Electronics and Robotics Club (ERC), BITS Goa

copyright: 'Copyright &copy; 2020 Electronics and Robotics Club (ERC), BITS Goa'

theme:
  name: 'material'
  language: en
  icon:
    logo: material/book-open-page-variant
  favicon: images/erc_logo.png
  features:
    - tabs
  palette:
    primary: green
    accent: green

repo_name: 'handbook'
repo_url: 'https://github.com/ERC-BPGC/handbook'

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/erc_bpgc

    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/ElectronicsAndRoboticsClub

    - icon: fontawesome/brands/github
      link: https://github.com/ERC-BPGC

    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/electronics-robotics-club-bits-goa/


markdown_extensions:
  - admonition
  - codehilite

google_analytics:
  - UA-173174352-1
  - auto
  
  
nav:
  - Home: index.md

  - Overview:
    - What is Robotics?: overview/what_is_robotics.md
    - Key Areas: overview/key_areas.md
    - Reference Material: overview/reference_material.md

  - Automation:
    - Introduction: automation/intro.md
    - ROS:
      - Setting Up: automation/ROS/setting_up.md
      - Getting Started with ROS: automation/ROS/ros.md

  - Electronics:
    - Introduction: electronics/intro.md

  - Mechanical:
    - Introduction: mechanical/intro.md

  - Simulation:
    - Introduction: simulation/intro.md

  - About Us: about.md
