name: Generate Changelog
on: 
  push:
    paths:
    - 'docs/**'
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Update Changelog
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@v1
      
    - name: Set up changelog
      uses: heinrichreimer/action-github-changelog-generator@v2.1.1



