name: Generate Changelog
on: 
  push:
    paths:
    - 'docs/**'
    paths-ignore:
    - '**.yml'
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Update Changelog
    runs-on: ubuntu-latest
    steps:
    - name: Generate changelog
      uses: heinrichreimer/action-github-changelog-generator@v2.1.1



